package view;


import model.Satellite;
import util.EarthUtil;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;

/**
 * @author Mohammad
 */
class CreateSatelliteDialog extends javax.swing.JDialog {

    CreateSatelliteDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        satelliteName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showFileChooser = new javax.swing.JButton();
        selectedFileName = new javax.swing.JLabel();
        saveSatellite = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        satelliteFour = new javax.swing.JComboBox<>();
        satelliteOne = new javax.swing.JComboBox<>();
        satelliteTwo = new javax.swing.JComboBox<>();
        satelliteThree = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusCycleRoot(false);
        setLocationByPlatform(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("نام");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ویژگی ها");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("اطلاعات دو خطی");
        jLabel4.setToolTipText("");

        showFileChooser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showFileChooser.setText("Browse...");
        showFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showFileChooserActionPerformed(evt);
            }
        });

        saveSatellite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveSatellite.setForeground(new java.awt.Color(102, 255, 255));
        saveSatellite.setText("ذخیره");
        saveSatellite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSatelliteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("سنجنده");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("توان تکنیکی");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("سطح تفسیر پذیری");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("فاصله تفکیک مکانی");

        satelliteFour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.2 تا 0.4", "0.4 تا 0.75", "0.75 تا 1.2", "1.2 تا 2.5", "2.5 تا 4.5", "4.5 تا 9", "بیش از 9 متر" }));

        satelliteOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "پانکروماتیک", "چند طیفی", "حرارتی", "ابر طیفی", "رادار روزنه مصنوعی" }));

        satelliteTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "قدرت تفکیک طیفی", "قدرت تفکیک زمانی", "قدرت تفکیک رادیو متریک" }));

        satelliteThree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "آشکار سازی", "تمایز", "شناسایی" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(satelliteName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(satelliteTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(satelliteOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(satelliteThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(satelliteFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(selectedFileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(showFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 2, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveSatellite, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(satelliteName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(satelliteOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(satelliteTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(satelliteThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(satelliteFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(selectedFileName)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(showFileChooser))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveSatellite, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

/***************************************************************************************/
/************************************ METHODS ******************************************/
    private File selectedFile;

    private void showFileChooserActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileDialog = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
//        fileDialog.setFileFilter(filter);
        fileDialog.addChoosableFileFilter(new FileNameExtensionFilter(".txt", "txt"));
        fileDialog.setAcceptAllFileFilterUsed(false);
        int returnVal = fileDialog.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileDialog.getSelectedFile();
            selectedFileName.setText(selectedFile.getName());
        }
    }

    private void saveSatelliteActionPerformed(java.awt.event.ActionEvent evt) {

        Satellite satellite = new Satellite();
        FileInputStream inputStream;
        FileOutputStream outputStream;
        try {
            File file = new File("src/resource/tle/" + selectedFile.getName());
            boolean newFileCreated = file.createNewFile();
            if (newFileCreated) {

                inputStream = new FileInputStream(selectedFile);
                outputStream = new FileOutputStream(file);
                byte[] buffer = new byte[1024];
                int i;
                while ((i = inputStream.read(buffer)) > 0) {
                    outputStream.write(buffer, 0, i);
                }

                satellite.setDisplayName(satelliteName.getText());
                satellite.setSatelliteOne(satelliteOne.getSelectedIndex());
                satellite.setSatelliteTwo(satelliteTwo.getSelectedIndex());
                satellite.setSatelliteThree(satelliteThree.getSelectedIndex());
                satellite.setSatelliteFour(satelliteFour.getSelectedIndex());
                satellite.setTleFile(selectedFile.getName());
                boolean isAddedSatellite = EarthUtil.addSatellite(satellite);
                if (isAddedSatellite) {
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "اطلاعات با موفقست ذخیره شد", "موفق",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "فایل ذخیره شد ولی ماهواره ذخیره نشد", "نا موفق", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                this.dispose();
                JOptionPane.showMessageDialog(null, "خطا در ذخیره اطلاعات", "نا موفق", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            this.dispose();
            JOptionPane.showMessageDialog(null, "خطا در ذخیره اطلاعات", "نا موفق", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();

        }


    }


/******************************************************************************************/
/************************************ VARIABLES *******************************************/
/******************************************************************************************/

// Variables declaration - do not modify
private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> satelliteFour;
    private javax.swing.JTextField satelliteName;
    private javax.swing.JComboBox<String> satelliteOne;
    private javax.swing.JComboBox<String> satelliteThree;
    private javax.swing.JComboBox<String> satelliteTwo;
    private javax.swing.JButton saveSatellite;
    private javax.swing.JLabel selectedFileName;
    private javax.swing.JButton showFileChooser;
    // End of variables declaration
}

